In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from plyfile import PlyData

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [4]:
ply_file_path = '../data/scans/scene0000_00/scene0000_00_vh_clean_2.ply'

ply_data = PlyData.read(ply_file_path)
print(ply_data)

# Accessing vertex data
vertex = ply_data['vertex']
print('\nvertex data')
print(len(vertex.properties))
for prop in vertex.properties:
    print(f"{prop.name}: {vertex[prop.name][:10]}")  # Display the first 10 values for each property

ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 81369
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 153587
property list uchar int vertex_indices
end_header

vertex data
7
x: [0.5324214  0.53404164 0.544779   0.5319752  0.52005076 0.53090763
 0.5435133  0.5211338  0.5306945  0.5262134 ]
y: [4.5172734 4.552089  4.4811263 4.5118823 4.525821  4.4639053 4.52379
 4.5587955 4.4245367 4.4974585]
z: [0.26304942 0.262302   0.17396316 0.1781445  0.15788905 0.22248712
 0.23870371 0.0829171  0.24097411 0.2422304 ]
red: [101  88  39 132 101 100  66  92 101 113]
green: [107  83  39 117  88 100  55  75 100 108]
blue: [ 90  78  35 108  76  82  56  51  86  88]
alpha: [255 255 255 255 255 255 255 255 255 255]


In [7]:
for i in range(10):
    print(vertex[i])

(0.5324214, 4.5172734, 0.26304942, 101, 107, 90, 255)
(0.53404164, 4.552089, 0.262302, 88, 83, 78, 255)
(0.544779, 4.4811263, 0.17396316, 39, 39, 35, 255)
(0.5319752, 4.5118823, 0.1781445, 132, 117, 108, 255)
(0.52005076, 4.525821, 0.15788905, 101, 88, 76, 255)
(0.53090763, 4.4639053, 0.22248712, 100, 100, 82, 255)
(0.5435133, 4.52379, 0.23870371, 66, 55, 56, 255)
(0.5211338, 4.5587955, 0.0829171, 92, 75, 51, 255)
(0.5306945, 4.4245367, 0.24097411, 101, 100, 86, 255)
(0.5262134, 4.4974585, 0.2422304, 113, 108, 88, 255)


In [3]:
sample_count = 7
print(f"\nFirst {sample_count} vertices:")
for i in range(sample_count):
    point = {prop.name: vertex[prop.name][i] for prop in vertex.properties}
    print(point)


First 7 vertices:
{'x': 0.5324214, 'y': 4.5172734, 'z': 0.26304942, 'red': 101, 'green': 107, 'blue': 90, 'alpha': 255}
{'x': 0.53404164, 'y': 4.552089, 'z': 0.262302, 'red': 88, 'green': 83, 'blue': 78, 'alpha': 255}
{'x': 0.544779, 'y': 4.4811263, 'z': 0.17396316, 'red': 39, 'green': 39, 'blue': 35, 'alpha': 255}
{'x': 0.5319752, 'y': 4.5118823, 'z': 0.1781445, 'red': 132, 'green': 117, 'blue': 108, 'alpha': 255}
{'x': 0.52005076, 'y': 4.525821, 'z': 0.15788905, 'red': 101, 'green': 88, 'blue': 76, 'alpha': 255}
{'x': 0.53090763, 'y': 4.4639053, 'z': 0.22248712, 'red': 100, 'green': 100, 'blue': 82, 'alpha': 255}
{'x': 0.5435133, 'y': 4.52379, 'z': 0.23870371, 'red': 66, 'green': 55, 'blue': 56, 'alpha': 255}


In [9]:
for i in range(10):
    print(ply_data["face"][i])

(array([   9, 5007, 5754], dtype=int32),)
(array([5008, 5007,    9], dtype=int32),)
(array([5008,    0, 8007], dtype=int32),)
(array([6, 1, 9], dtype=int32),)
(array([385,   1,   6], dtype=int32),)
(array([   0,    1, 8007], dtype=int32),)
(array([   0, 5008,    9], dtype=int32),)
(array([9, 1, 0], dtype=int32),)
(array([  4, 368,   3], dtype=int32),)
(array([368,   4, 361], dtype=int32),)
